# Generated by Django 3.0.5 on 2020-12-20 06:23

import MongoDB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0004_auto_20201219_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=MongoDB.models.File.directory),
        ),
    ]
