# Generated by Django 3.0.5 on 2020-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0005_auto_20201220_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='eachfile',
            field=models.TextField(blank=True),
        ),
    ]
