# Generated by Django 3.0.5 on 2020-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0006_file_eachfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='modelname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
