# Generated by Django 3.0.5 on 2021-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0007_file_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filedetail',
            field=models.TextField(blank=True),
        ),
    ]
