# Generated by Django 3.0.5 on 2021-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0010_extractfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractfile',
            name='coordinates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractfile',
            name='fieldextract',
            field=models.TextField(blank=True),
        ),
    ]
