# Generated by Django 3.0.5 on 2021-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0011_auto_20210126_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractfile',
            name='eachfile',
            field=models.TextField(blank=True),
        ),
    ]
