# Generated by Django 3.0.5 on 2021-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MongoDB', '0012_extractfile_eachfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractfile',
            name='originalname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
